
  - name: "install python for Ansible."
    apt:
      pkg: 
        - python3
      state: latest
      update_cache: true

  - name: "install Node.js."
    apt:
      pkg: 
        - npm
      state: latest
      update_cache: true

  - name: "install PM2 for Node.js."
    shell:
      cmd: |
        npm install pm2 -g

  - name: "Persist environment variables."
    shell:
      cmd: |
        ENVIRONMENT=/home/ubuntu/web/development.env
        echo "" > $ENVIRONMENT
        echo "TYPEORM_CONNECTION=$TYPEORM_CONNECTION" >> $ENVIRONMENT
        echo "TYPEORM_ENTITIES=$TYPEORM_ENTITIES" >> $ENVIRONMENT
        echo "TYPEORM_HOST=$TYPEORM_HOST" >> $ENVIRONMENT
        echo "TYPEORM_PORT=$TYPEORM_PORT" >> $ENVIRONMENT
        echo "TYPEORM_USERNAME=$TYPEORM_USERNAME" >> $ENVIRONMENT
        echo "TYPEORM_PASSWORD=$TYPEORM_PASSWORD" >> $ENVIRONMENT
        echo "TYPEORM_DATABASE=$TYPEORM_DATABASE" >> $ENVIRONMENT
        echo "TYPEORM_MIGRATIONS=$TYPEORM_MIGRATIONS" >> $ENVIRONMENT
        echo "TYPEORM_MIGRATIONS_DIR=$TYPEORM_MIGRATIONS_DIR" >> $ENVIRONMENT
        cat $ENVIRONMENT
